"""Typer commands for the AWX / AAP domain.

Top-level commands (``ping``, ``apply``, ``save``, ``jobs``) live here.
Per-resource sub-apps (``job-templates``, ``projects``, …) are
generated by :func:`make_resource_app` and attached at module load.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterable
from pathlib import Path

import typer
from rich.console import Console
from untaped import (
    ColumnsOption,
    ConfigError,
    FormatOption,
    OutputFormat,
    ProfileOverrideOption,
    format_output,
    get_config_section,
    get_core_settings,
    parse_kv_pairs,
    profile_override,
    read_identifiers,
    report_errors,
    resolve_each,
)

from untaped_awx.application import (
    GetJob,
    ListJobs,
    Ping,
    StreamJobEvents,
    TailJobLogs,
    WatchJob,
)
from untaped_awx.application.apply_file import APPLY_PARALLEL_CAP
from untaped_awx.cli._apply_runner import resolve_apply_file, run_apply
from untaped_awx.cli._context import open_context
from untaped_awx.cli._event_render import render_event_text
from untaped_awx.cli._factory import make_resource_app
from untaped_awx.cli._save_runner import run_save_batch
from untaped_awx.cli.options import OrganizationOption
from untaped_awx.cli.test_commands import app as test_app
from untaped_awx.cli.unified_templates_commands import app as unified_templates_app
from untaped_awx.cli.workflow_node_commands import register_nodes_command
from untaped_awx.domain import Job, JobEvent
from untaped_awx.infrastructure import AwxClient, AwxConfig
from untaped_awx.infrastructure.specs import ALL_SPECS

app = typer.Typer(
    name="awx",
    help="Talk to Ansible Automation Platform / AWX.",
    no_args_is_help=True,
)


@app.callback()
def _callback() -> None:
    """Talk to Ansible Automation Platform / AWX."""


# ---- ping ----


@app.command("ping")
def ping_command(
    profile: ProfileOverrideOption = None,
    fmt: FormatOption = "table",
    columns: ColumnsOption = None,
) -> None:
    """Check control-plane health."""
    with report_errors(), profile_override(profile):
        settings = get_core_settings()
        config = get_config_section("awx", AwxConfig)
        with AwxClient(config, http=settings.http) as client:
            status = Ping(client)()
        typer.echo(format_output([status.model_dump()], fmt=fmt, columns=columns))


# ---- top-level apply (multi-kind, file or directory) ----


@app.command("apply", no_args_is_help=True)
def apply_command(
    file: Path | None = typer.Argument(None, help="YAML file or directory."),
    file_opt: Path | None = typer.Option(
        None,
        "--file",
        "-f",
        help="Deprecated alias; prefer the positional FILE.",
    ),
    yes: bool = typer.Option(False, "--yes", help="Actually write (default is preview only)."),
    fail_fast: bool = typer.Option(False, "--fail-fast", help="Abort on first error."),
    parallel: int = typer.Option(
        1,
        "--parallel",
        "-j",
        help=(
            "Concurrent doc writes within a kind. Cross-kind ordering is "
            "preserved; phase 2 (membership reconciliation) stays serial. "
            f"Capped at {APPLY_PARALLEL_CAP} (matches the HTTP connection pool default)."
        ),
    ),
    profile: ProfileOverrideOption = None,
    fmt: OutputFormat = typer.Option("table", "--format", help="Result-table format."),
    columns: list[str] | None = typer.Option(None, "--columns", "-c"),
) -> None:
    """Apply YAML docs in dependency order. Default = preview; ``--yes`` writes."""
    target = resolve_apply_file(file, file_opt)
    with report_errors(), open_context(profile) as ctx:
        run_apply(
            ctx,
            target,
            write=yes,
            fail_fast=fail_fast,
            fmt=fmt,
            columns=columns,
            parallel=parallel,
        )


# ---- top-level save ----


def _warn_legacy_all(value: bool) -> bool:
    """Emit the legacy-``--all`` deprecation warning on stderr."""
    if value:
        typer.echo(
            "warning: --all is deprecated; use --all-kinds instead. "
            "--all will be removed in a future release.",
            err=True,
        )
    return value


def _reject_duplicate_org_scope(
    organization: str | None,
    filters: dict[str, str],
) -> None:
    if organization is None:
        return
    for key in filters:
        if _is_raw_org_scope_filter(key):
            raise typer.BadParameter(
                f"do not combine --org/--organization with --filter {key}=...; "
                "use --org for organization-scoped bulk save"
            )


def _is_raw_org_scope_filter(key: str) -> bool:
    return (
        key == "organization"
        or key.startswith("organization__")
        or (key == "inventory__organization" or key.startswith("inventory__organization__"))
    )


@app.command("save", no_args_is_help=True)
def save_top_command(
    out_dir: Path = typer.Option(
        ..., "--out-dir", help="Directory to write per-resource files into."
    ),
    all_kinds: bool = typer.Option(
        False,
        "--all-kinds",
        help="Save every saveable kind (iterate the type axis).",
    ),
    # TODO(drop-legacy-all-alias): remove this Option and the
    # _warn_legacy_all callback above in the next minor release.
    legacy_all: bool = typer.Option(
        False,
        "--all",
        hidden=True,
        callback=_warn_legacy_all,
        help="Deprecated alias for --all-kinds.",
    ),
    kind: str | None = typer.Option(
        None,
        "--kind",
        help=(
            "Limit save to a single kind. Accepts a CLI name "
            "(job-templates) or a domain kind (JobTemplate)."
        ),
    ),
    organization: OrganizationOption = None,
    filter_: list[str] | None = typer.Option(
        None,
        "--filter",
        help=(
            "Expert server-side filter, KEY=VALUE (repeatable). Passed "
            "verbatim to AWX for each saved kind. For organization backups, "
            "prefer --org so each kind gets a compatible scope."
        ),
    ),
    print_paths: bool = typer.Option(
        False,
        "--print-paths",
        help=(
            "Emit written filenames on stdout instead of the YAML envelopes. "
            "Legacy shape — preserved for scripts that `git add` the dump."
        ),
    ),
    profile: ProfileOverrideOption = None,
) -> None:
    """Bulk-save resources to a directory.

    ``save --all-kinds --out-dir DIR`` writes one file per resource
    using the full identity in the filename so same-named records
    across organizations don't collide:
    ``<Kind>[__<org>][__<parent_kind>__[<parent_org>__]<parent_name>]__<name>.yml``.
    Kinds with read-only fidelity (Credential) are skipped with a
    one-line note.

    Default stdout shape is a multi-doc YAML stream of the same
    envelopes the files contain, so the dump pipes straight into
    ``apply`` (``---``-separated docs, one per record). Pass
    ``--print-paths`` to swap stdout for the written-file list
    instead.
    """
    all_kinds = all_kinds or legacy_all
    if not all_kinds and not kind:
        raise typer.BadParameter("pass --all-kinds or --kind")
    filters = parse_kv_pairs(filter_, flag="--filter")
    _reject_duplicate_org_scope(organization, filters)

    with report_errors(), open_context(profile) as ctx:
        run_save_batch(
            ctx,
            out_dir=out_dir,
            all_kinds=all_kinds,
            kind=kind,
            filters=filters,
            organization=organization,
            print_paths=print_paths,
        )


# ---- jobs (read-only execution records) ----


jobs_app = typer.Typer(name="jobs", help="Inspect AWX jobs.", no_args_is_help=True)


@jobs_app.callback()
def _jobs_callback() -> None:
    """Inspect AWX jobs."""


_JOB_KIND_HELP = (
    "Execution kind. Defaults to 'job' (a JobTemplate run). Other values: "
    "workflow_job, project_update, inventory_update, ad_hoc_command. "
    "Hits the matching AWX collection (e.g. workflow_jobs/<id>/)."
)


def _as_job_id(value: str) -> int:
    """Parse a stdin/positional job id; surface bad input as a per-id error.

    ``resolve_each`` only catches :class:`UntapedError`, so a raw
    ``ValueError`` from a malformed stdin line would otherwise abort the
    batch — wrapping in :class:`ConfigError` lets the loop continue and
    emit a per-id ``error:`` row for the bad value alongside the good ones.
    """
    try:
        return int(value)
    except ValueError as exc:
        raise ConfigError(f"not a numeric job id: {value!r}") from exc


@jobs_app.command("list")
def jobs_list(
    status: str | None = typer.Option(
        None,
        "--status",
        help="Filter by AWX status (e.g. running, successful, failed).",
    ),
    filter_: list[str] | None = typer.Option(
        None,
        "--filter",
        help="Server-side filter, KEY=VALUE (repeatable). Forwarded verbatim.",
    ),
    limit: int | None = typer.Option(None, "--limit", help="Cap result count."),
    kind: str = typer.Option("job", "--kind", help=_JOB_KIND_HELP),
    profile: ProfileOverrideOption = None,
    fmt: OutputFormat = typer.Option("table", "--format", "-f", help="Output format."),
    columns: ColumnsOption = None,
) -> None:
    """List recent AWX jobs (newest first)."""
    filters = parse_kv_pairs(filter_, flag="--filter")
    if status:
        filters["status"] = status
    with report_errors(), open_context(profile) as ctx:
        records = list(ListJobs(ctx.jobs)(kind=kind, params=filters, limit=limit))
    cols = list(columns) if columns else ["id", "name", "status"]
    typer.echo(format_output(records, fmt=fmt, columns=cols))


@jobs_app.command("get", no_args_is_help=True)
def jobs_get(
    job_ids: list[str] | None = typer.Argument(None, help="Job ID(s)."),
    stdin: bool = typer.Option(False, "--stdin", help="Read job ids from stdin (one per line)."),
    kind: str = typer.Option("job", "--kind", help=_JOB_KIND_HELP),
    profile: ProfileOverrideOption = None,
    fmt: OutputFormat = typer.Option("yaml", "--format", "-f"),
    columns: ColumnsOption = None,
) -> None:
    """Fetch one or more jobs by id."""
    # Hoisted so they're bound even if ``report_errors`` swallows the
    # body — keeps the post-``with`` exit-code dispatch safe.
    records: list[dict[str, object]] = []
    any_failed = False
    with report_errors(), open_context(profile) as ctx:
        ids = read_identifiers(list(job_ids or []), stdin=stdin)
        records, any_failed = resolve_each(
            ids, lambda n: GetJob(ctx.jobs)(kind=kind, job_id=_as_job_id(n))
        )
    if records:
        typer.echo(format_output(records, fmt=fmt, columns=list(columns) if columns else []))
    if any_failed:
        raise typer.Exit(code=1)


@jobs_app.command("events", no_args_is_help=True)
def jobs_events(
    job_ids: list[str] | None = typer.Argument(None, help="Job ID(s)."),
    stdin: bool = typer.Option(False, "--stdin", help="Read job ids from stdin (one per line)."),
    follow: bool = typer.Option(False, "--follow", help="Tail events live until terminal."),
    from_counter: int = typer.Option(
        0, "--from-counter", help="Skip events with counter <= this value."
    ),
    filter_: list[str] | None = typer.Option(
        None,
        "--filter",
        help="Server-side AWX filter, KEY=VALUE (repeatable). E.g. event=runner_on_failed.",
    ),
    kind: str = typer.Option("job", "--kind", help=_JOB_KIND_HELP),
    profile: ProfileOverrideOption = None,
    fmt: FormatOption = "table",
    columns: ColumnsOption = None,
) -> None:
    """Stream the structured per-task event log for one or more jobs.

    Without ``--follow`` this drains each job's event log and exits;
    with ``--follow`` it polls AWX every 2s until each job is terminal.
    Filters reach AWX directly so you can scope server-side, e.g.
    ``--filter event=runner_on_failed --filter host=web-01``.

    Multiple ids drain serially with a ``[<id>]`` stderr breadcrumb
    between jobs. For a single id, output is identical to today.

    Multi-id non-follow drains emit one format block per job — for
    ``--format json``/``yaml``/``table`` that means N separately framed
    documents, not one merged document. Each row carries a ``job`` field
    so jq pipelines that need a single document should use
    ``--format raw`` (concatenated lines) or ``--follow --format json``
    (NDJSON streams unframed).
    """
    filters = parse_kv_pairs(filter_, flag="--filter")
    cols = list(columns) if columns else ["counter", "event", "host_name", "task"]
    # Hoisted so post-``with`` exit dispatch is safe regardless of body outcome.
    any_failed = False
    with report_errors(), open_context(profile) as ctx:
        ids = read_identifiers(list(job_ids or []), stdin=stdin)
        show_breadcrumb = len(ids) > 1

        def _events_for_id(n: str) -> None:
            job_id = _as_job_id(n)
            record = GetJob(ctx.jobs)(kind=kind, job_id=job_id)
            job = Job.model_validate({**record, "kind": kind})
            if show_breadcrumb:
                typer.echo(f"[{job_id}]", err=True)
            events = StreamJobEvents(ctx.monitor)(
                job, from_counter=from_counter, filters=filters, follow=follow
            )
            _emit_events(events, fmt=fmt, cols=cols, follow=follow)

        _, any_failed = resolve_each(ids, _events_for_id)
    if any_failed:
        raise typer.Exit(code=1)


def _emit_events(
    events: Iterable[JobEvent],
    *,
    fmt: OutputFormat,
    cols: list[str],
    follow: bool,
) -> None:
    """Lifted out of the per-id closure so multi-id callers reuse
    the single-id rendering verbatim — no behavioural drift between
    batch and single modes."""
    if not follow:
        # One-shot drain: collect everything then format as a single
        # table / json document so columns line up and yaml stays a
        # well-formed list.
        rows = [ev.model_dump() for ev in events]
        typer.echo(format_output(rows, fmt=fmt, columns=cols))
        return
    if fmt == "table":
        # Table mode under --follow renders each event as a colored
        # human-readable line (PLAY [..] / TASK [..] / "  ok: host"),
        # similar to the AWX UI's Output tab. ``rich.console.Console``
        # auto-detects TTY: ANSI on a real terminal, plain text when
        # piped or redirected. No new dependency — Rich is already
        # used for table rendering elsewhere.
        console = Console(highlight=False)
        for ev in events:
            console.print(render_event_text(ev))
        return
    # Other formats (json/yaml/raw) stream one structured row at a
    # time — useful for ``--follow | jq``-style pipelines.
    # JSON streams as NDJSON (one bare object per line, no enclosing
    # array brackets) to match ``kubectl get -w -o json`` and so
    # ``jq`` can ingest it directly without ``jq -s '.[]'``.
    if fmt == "json":
        for ev in events:
            row = {c: ev.model_dump().get(c) for c in cols}
            typer.echo(json.dumps(row, default=str))
        return
    for ev in events:
        line = format_output([ev.model_dump()], fmt=fmt, columns=cols)
        typer.echo(line)


def _emit_log_lines(
    lines: Iterable[str],
    *,
    fmt: OutputFormat,
    cols: list[str] | None,
    follow: bool,
) -> None:
    """Render the stdout of a job. Sibling of :func:`_emit_events`.

    ``cols=None`` (vs ``_emit_events``'s required ``list[str]``) means
    "emit every field of the row" — logs has no default columns whereas
    events has ``["counter","event","host_name","task"]``.
    """
    if not follow:
        rendered = format_output([{"line": line} for line in lines], fmt=fmt, columns=cols)
        if rendered:
            typer.echo(rendered)
        return
    # JSON streams as NDJSON (one bare object per line, no enclosing
    # array brackets) to match ``jobs events --follow --format json``
    # and so ``jq`` can ingest it directly without ``jq -s '.[]'``.
    if fmt == "json":
        for line in lines:
            row: dict[str, object] = {"line": line}
            if cols is not None:
                row = {c: row.get(c) for c in cols}
            typer.echo(json.dumps(row, default=str))
        return
    if fmt == "raw":
        # Skip the no-op ``format_output`` round-trip — raw lines are
        # already the final shape, and the per-line wrap is the hot path
        # on a 100k-line follow stream. ``cols`` is ignored here: log
        # rows are single-field (``line``), so any projection is either
        # the identity or a path miss; the only meaningful value is
        # ``--columns line``, which is what users pass.
        for line in lines:
            typer.echo(line)
        return
    # No Rich table branch (unlike ``_emit_events``): log lines are
    # unstructured text, so ``--format table --follow`` falls through
    # to per-line ``format_output`` like yaml does. Table-per-line is
    # silly but the cost is on the user who asked for it.
    for line in lines:
        typer.echo(format_output([{"line": line}], fmt=fmt, columns=cols))


@jobs_app.command("logs", no_args_is_help=True)
def jobs_logs(
    job_ids: list[str] | None = typer.Argument(None, help="Job ID(s)."),
    stdin: bool = typer.Option(False, "--stdin", help="Read job ids from stdin (one per line)."),
    follow: bool = typer.Option(False, "--follow", "-f", help="Tail until terminal."),
    tail: int | None = typer.Option(
        None, "--tail", help="Show only the last N historical lines before following."
    ),
    grep: str | None = typer.Option(
        None, "--grep", help="Client-side regex; only matching lines are printed."
    ),
    ignore_case: bool = typer.Option(False, "--ignore-case", "-i", help="Case-insensitive --grep."),
    kind: str = typer.Option("job", "--kind", help=_JOB_KIND_HELP),
    fmt: OutputFormat = typer.Option(
        "raw", "--format", help="Output format (json|yaml|table|raw)."
    ),
    columns: ColumnsOption = None,
    profile: ProfileOverrideOption = None,
) -> None:
    """Print the stdout of one or more jobs. Supports follow / tail / grep.

    Multiple ids drain serially with a ``[<id>]`` stderr breadcrumb
    between jobs. For a single id, output is identical to today.
    """
    if grep is not None:
        # Compile here so an invalid regex fails fast as a clean
        # ``BadParameter`` (cleanly mapped to exit 2 by Typer) rather than
        # leaking a ``re.error`` traceback through ``report_errors`` later.
        try:
            re.compile(grep, re.IGNORECASE if ignore_case else 0)
        except re.error as exc:
            raise typer.BadParameter(f"--grep {grep!r} is not a valid regex: {exc}") from exc
    # Hoisted so post-``with`` exit dispatch is safe regardless of body outcome.
    any_failed = False
    with report_errors(), open_context(profile) as ctx:
        ids = read_identifiers(list(job_ids or []), stdin=stdin)
        show_breadcrumb = len(ids) > 1
        cols = list(columns) if columns else None

        def _logs_for_id(n: str) -> None:
            job_id = _as_job_id(n)
            record = GetJob(ctx.jobs)(kind=kind, job_id=job_id)
            job = Job.model_validate({**record, "kind": kind})
            if show_breadcrumb:
                typer.echo(f"[{job_id}]", err=True)
            lines = TailJobLogs(ctx.monitor)(
                job, follow=follow, grep=grep, ignore_case=ignore_case, tail=tail
            )
            _emit_log_lines(lines, fmt=fmt, cols=cols, follow=follow)

        _, any_failed = resolve_each(ids, _logs_for_id)
    if any_failed:
        raise typer.Exit(code=1)


@jobs_app.command("wait", no_args_is_help=True)
def jobs_wait(
    job_ids: list[str] | None = typer.Argument(None, help="Job ID(s)."),
    stdin: bool = typer.Option(False, "--stdin", help="Read job ids from stdin (one per line)."),
    timeout: float | None = typer.Option(
        None, "--timeout", help="Seconds to wait before giving up (applies per id)."
    ),
    kind: str = typer.Option("job", "--kind", help=_JOB_KIND_HELP),
    fmt: OutputFormat = typer.Option(
        "table", "--format", "-f", help="Output format (json|yaml|table|raw)."
    ),
    columns: ColumnsOption = None,
    profile: ProfileOverrideOption = None,
) -> None:
    """Block until each named job reaches a terminal state.

    Exits non-zero when any job times out or any id fails to resolve —
    same contract as ``awx test``. Multiple ids drain serially; the
    ``--timeout`` budget applies per id.
    """
    # Hoisted so post-``with`` exit dispatch is safe regardless of body outcome.
    records: list[dict[str, object]] = []
    any_failed = False
    timed_out: list[int] = []
    with report_errors(), open_context(profile) as ctx:
        ids = read_identifiers(list(job_ids or []), stdin=stdin)

        def _wait_one(n: str) -> dict[str, object]:
            job_id = _as_job_id(n)
            record = GetJob(ctx.jobs)(kind=kind, job_id=job_id)
            job = Job.model_validate({**record, "kind": kind})
            final = WatchJob(ctx.repo)(job, timeout=timeout)
            if not final.is_terminal:
                timed_out.append(job_id)
            return final.model_dump()

        records, any_failed = resolve_each(ids, _wait_one)
    if records:
        typer.echo(format_output(records, fmt=fmt, columns=columns))
    for job_id in timed_out:
        typer.echo(f"timeout: job {job_id} did not reach terminal state", err=True)
    if any_failed or timed_out:
        raise typer.Exit(code=1)


app.add_typer(jobs_app, name="jobs")
app.add_typer(unified_templates_app, name="unified-templates")
app.add_typer(test_app, name="test")


# ---- per-resource sub-apps (factory-generated) ----


for spec in ALL_SPECS:
    if not spec.commands:
        # Catalog-only stubs (e.g. ExecutionEnvironment, Label) exist purely
        # so :class:`FkResolver` can resolve names → ids for launch-payload
        # FKs. They have no user-facing CLI surface.
        continue
    sub_app = make_resource_app(spec)
    if spec.kind == "WorkflowJobTemplate":
        register_nodes_command(sub_app)
    app.add_typer(sub_app, name=spec.cli_name)
